package ur.azizairo.foundation.model.tasks.exceptions

class CancelledException(originalException: Exception? = null): Exception(originalException)  {

}
